// src/pages/products/SolarInverters.jsx
import React from "react";
import styled from "styled-components";
import {
  ArrowRight,
  Cpu,
  Sun,
  Battery,
  Home,
  Zap,
  ShieldAlert,
  PowerOff,
  Award,
  Activity,
  Microchip,
  Waves,
  LineChart,
  ArrowLeftRight,
  Clock,
  CheckCircle2,
} from "lucide-react";
import Animated from "../../components/common/Animated";

const safetyFeatures = [
  {
    title: "AFCI Protection",
    icon: <ShieldAlert size={28} />,
    description:
      "Arc Fault Circuit Interrupter technology detects electrical sparks and shuts down the system in milliseconds to prevent fire hazards.",
  },
  {
    title: "Rapid Shutdown",
    icon: <PowerOff size={28} />,
    description:
      "In emergency situations, the inverter can instantly reduce rooftop wiring voltage to safe levels below 30V, protecting maintenance workers.",
  },
  {
    title: "BEE 2026 Compliance",
    icon: <Award size={28} />,
    description:
      "Modern solar inverters comply with updated efficiency standards, achieving 98% or higher conversion efficiency.",
  },
];

const engineeringFeatures = [
  {
    title: "SiC Semiconductor Technology",
    icon: <Cpu size={20} />, // Fallback to Cpu if Microchip isn't available in specific lucide versions
    description:
      "Silicon carbide components reduce heat generation and energy loss during power conversion.",
  },
  {
    title: "99% Peak Efficiency",
    icon: <Zap size={20} />,
    description:
      "Advanced inverter designs achieve extremely high power conversion efficiency.",
  },
  {
    title: "Multi-MPPT Architecture",
    icon: <Activity size={20} />,
    description:
      "Multiple independent MPPT trackers optimize power production on complex rooftops with varying angles or shading.",
  },
  {
    title: "Pure Sine Wave Output",
    icon: <Waves size={20} />,
    description:
      "Maintains THD below 3%, delivering stable power suitable for sensitive electronic equipment.",
  },
];

const gridInteractionFeatures = [
  {
    title: "Hybrid Energy Flow",
    icon: <ArrowLeftRight size={28} />,
    description:
      "Inverters allow bi-directional energy movement between solar panels, batteries, and the electrical grid.",
  },
  {
    title: "Dynamic Export Control",
    icon: <LineChart size={28} />,
    description:
      "Systems can synchronize with utility pricing to maximize financial returns when exporting solar power to the grid.",
  },
  {
    title: "Zero Transfer Time",
    icon: <Clock size={28} />,
    description:
      "Hybrid inverter systems switch instantly to battery power during grid outages, ensuring uninterrupted energy supply.",
  },
];

const SolarInverters = () => {
  return (
    <PageWrapper>
      {/* 1️⃣ HERO SECTION */}
      <HeroSection>
        <HeroPattern />
        <Container>
          <HeroGrid>
            <HeroContent>
              <Animated animation="fadeInDown" duration={0.6}>
                <Eyebrow>Solar Energy Infrastructure</Eyebrow>
                <HeroHeading>Solar Inverters</HeroHeading>
                <HeroSubheading>
                  The intelligent gateway between solar panels, energy storage,
                  and the electrical grid.
                </HeroSubheading>
                <HeroDescription>
                  Solar inverters convert the direct current (DC) generated by
                  solar panels into usable alternating current (AC) electricity
                  for homes and businesses. Modern inverter systems act as smart
                  energy hubs that manage energy flow, monitor system
                  performance, and ensure safe grid interaction.
                </HeroDescription>
                <CTAButton href="#technology">
                  Explore Energy Intelligence <ArrowRight size={20} />
                </CTAButton>
              </Animated>
            </HeroContent>

            <HeroImageArea>
              <Animated animation="fadeIn" delay={0.2} duration={0.8}>
                <ImageWrapper>
                  <img
                    src="https://plus.unsplash.com/premium_photo-1671808063085-c307723bfa2f?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                    alt="Solar Inverter System Installation"
                    loading="lazy"
                  />
                </ImageWrapper>
              </Animated>
            </HeroImageArea>
          </HeroGrid>
        </Container>
      </HeroSection>

      {/* 2️⃣ SMART ENERGY HUB CONCEPT */}
      <HubSection id="technology">
        <Container>
          <Animated animation="fadeInDown" duration={0.6}>
            <SectionTitle className="centered">
              The Smart Energy Hub
            </SectionTitle>
            <IntroText className="centered">
              Modern solar inverters function as the central control unit of a
              solar energy system. They manage energy flow between solar panels,
              batteries, and the electrical grid while ensuring optimal power
              conversion and system safety. By coordinating energy distribution,
              the inverter ensures that solar systems operate efficiently and
              reliably.
            </IntroText>
          </Animated>

          <Animated animation="fadeInUp" delay={0.2} duration={0.6}>
            <FlowDiagram>
              <FlowNode>
                <div className="icon-circle">
                  <Sun size={32} />
                </div>
                <span>Solar Panels</span>
              </FlowNode>

              <FlowArrow>
                <ArrowRight size={24} />
              </FlowArrow>

              <FlowNode className="highlight">
                <div className="icon-circle inverter-icon">
                  <Cpu size={36} />
                </div>
                <span>Inverter</span>
              </FlowNode>

              <FlowArrow>
                <ArrowRight size={24} />
              </FlowArrow>

              <FlowNode>
                <div className="icon-circle">
                  <Battery size={32} />
                </div>
                <span>Battery</span>
              </FlowNode>

              <FlowArrow>
                <ArrowRight size={24} />
              </FlowArrow>

              <FlowNode>
                <div className="icon-circle">
                  <Home size={32} />
                </div>
                <span>Grid / Home</span>
              </FlowNode>
            </FlowDiagram>
          </Animated>
        </Container>
      </HubSection>

      {/* 3️⃣ RAPID MPPT TECHNOLOGY */}
      <MpptSection>
        <Container>
          <SplitLayout>
            <MpptImageArea>
              <Animated animation="fadeInRight" duration={0.8}>
                <ImageWrapper className="tall">
                  <img
                    src="https://plus.unsplash.com/premium_photo-1682145601250-face8160cdc8?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                    alt="Solar power monitoring display"
                    loading="lazy"
                  />
                </ImageWrapper>
              </Animated>
            </MpptImageArea>

            <MpptContent>
              <Animated animation="fadeInLeft" duration={0.6}>
                <SectionTitle>Rapid Maximum Power Point Tracking</SectionTitle>
                <IntroText>
                  Modern inverters use Rapid MPPT (Maximum Power Point Tracking)
                  technology to continuously adjust power conversion and extract
                  the maximum possible energy from solar panels throughout the
                  day.
                </IntroText>

                <FeatureCardsWrapper>
                  <MpptFeatureCard>
                    <FeatureHeader>
                      <Activity size={24} className="feature-icon" />
                      <h4>Millisecond Tracking</h4>
                    </FeatureHeader>
                    <p>
                      Advanced MPPT systems track sunlight fluctuations in
                      milliseconds, maintaining optimal energy output even
                      during rapidly changing weather conditions.
                    </p>
                  </MpptFeatureCard>

                  <MpptFeatureCard>
                    <FeatureHeader>
                      <Zap size={24} className="feature-icon" />
                      <h4>Higher Daily Energy Yield</h4>
                    </FeatureHeader>
                    <p>
                      Rapid MPPT can generate up to 30% more energy compared to
                      older solar inverter technologies by minimizing conversion
                      lag.
                    </p>
                  </MpptFeatureCard>
                </FeatureCardsWrapper>
              </Animated>
            </MpptContent>
          </SplitLayout>
        </Container>
      </MpptSection>

      {/* 4️⃣ SAFETY & COMPLIANCE SYSTEMS */}
      <SafetySection>
        <Container>
          <Animated animation="fadeInDown" duration={0.6}>
            <SectionTitle className="centered">
              Integrated Safety Systems
            </SectionTitle>
          </Animated>

          <Grid3Col>
            {safetyFeatures.map((feature, index) => (
              <Animated
                key={index}
                animation="fadeInUp"
                delay={index * 0.15}
                duration={0.5}
              >
                <SafetyCard>
                  <IconBox>{feature.icon}</IconBox>
                  <CardTitle>{feature.title}</CardTitle>
                  <CardDesc>{feature.description}</CardDesc>
                </SafetyCard>
              </Animated>
            ))}
          </Grid3Col>
        </Container>
      </SafetySection>

      {/* 5️⃣ PROFESSIONAL INVERTER ENGINEERING */}
      <EngineeringSection>
        <Container>
          <SplitLayout className="reverse-mobile">
            <EngineeringContent>
              <Animated animation="fadeInLeft" duration={0.6}>
                <SectionTitle>Professional-Grade Power Conversion</SectionTitle>

                <EngineeringList>
                  {engineeringFeatures.map((item, index) => (
                    <EngineeringItem key={index}>
                      <EngineeringIcon>{item.icon}</EngineeringIcon>
                      <div>
                        <h4>{item.title}</h4>
                        <p>{item.description}</p>
                      </div>
                    </EngineeringItem>
                  ))}
                </EngineeringList>
              </Animated>
            </EngineeringContent>

            <EngineeringImageArea>
              <Animated animation="fadeInRight" duration={0.8}>
                <ImageWrapper>
                  <img
                    src="https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?q=80&w=1000&auto=format&fit=crop"
                    alt="Professional electrical control system"
                    loading="lazy"
                  />
                </ImageWrapper>
              </Animated>
            </EngineeringImageArea>
          </SplitLayout>
        </Container>
      </EngineeringSection>

      {/* 6️⃣ GRID INTERACTION & ENERGY AUTONOMY */}
      <GridInteractionSection>
        <Container>
          <Animated animation="fadeInDown" duration={0.6}>
            <SectionTitle className="centered">
              Grid-Interactive Energy Systems
            </SectionTitle>
          </Animated>

          <Grid3Col>
            {gridInteractionFeatures.map((feature, index) => (
              <Animated
                key={index}
                animation="fadeInUp"
                delay={index * 0.15}
                duration={0.5}
              >
                <InteractionCard>
                  <InteractionHeader>
                    <IconBox className="light">{feature.icon}</IconBox>
                    <CardTitle>{feature.title}</CardTitle>
                  </InteractionHeader>
                  <CardDesc>{feature.description}</CardDesc>
                </InteractionCard>
              </Animated>
            ))}
          </Grid3Col>
        </Container>
      </GridInteractionSection>

      {/* FINAL CTA SECTION */}
      <CtaSection>
        <Container>
          <Animated animation="fadeIn" duration={0.6}>
            <CtaWrapper>
              <CtaHeading>The Brain of Your Solar Energy System</CtaHeading>
              <CtaSubtext>
                Advanced inverter technology ensures safe, efficient, and
                intelligent power conversion for modern solar installations.
              </CtaSubtext>
              <CTAButton href="/solutions" className="center">
                Explore Solar Energy Systems <ArrowRight size={20} />
              </CTAButton>
            </CtaWrapper>
          </Animated>
        </Container>
      </CtaSection>
    </PageWrapper>
  );
};

export default SolarInverters;

// --- STYLED COMPONENTS ---

const PageWrapper = styled.div`
  width: 100%;
  overflow-x: hidden;
  background-color: var(--color-bg);
`;

const Container = styled.div`
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
  position: relative;
  z-index: 2;

  @media (max-width: 768px) {
    padding: 0 20px;
  }
`;

const SectionTitle = styled.h2`
  font-size: 2.5rem;
  font-weight: 800;
  color: var(--color-text);
  margin-bottom: 1.5rem;
  line-height: 1.2;
  letter-spacing: -0.5px;

  &.centered {
    text-align: center;
  }

  @media (max-width: 768px) {
    font-size: 2rem;
    margin-bottom: 1.25rem;
  }
`;

const IntroText = styled.p`
  font-size: 1.1rem;
  color: var(--color-text-secondary);
  line-height: 1.6;
  margin-bottom: 2.5rem;
  max-width: 800px;

  &.centered {
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }

  @media (max-width: 768px) {
    font-size: 1.05rem;
    text-align: left;
  }
`;

// --- 1️⃣ HERO SECTION ---
const HeroSection = styled.section`
  padding: 120px 0 80px;
  background-color: var(--color-surface-secondary);
  border-bottom: 1px solid var(--color-border-light);
  position: relative;
  overflow: hidden;

  @media (max-width: 768px) {
    padding: 100px 0 60px;
  }
`;

const HeroPattern = styled.div`
  position: absolute;
  inset: 0;
  background-image: radial-gradient(var(--color-border) 1px, transparent 1px);
  background-size: 30px 30px;
  opacity: 0.4;
  z-index: 1;
`;

const HeroGrid = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 60px;
  align-items: center;

  @media (max-width: 900px) {
    grid-template-columns: 1fr;
    gap: 40px;
  }
`;

const HeroContent = styled.div`
  display: flex;
  flex-direction: column;

  @media (max-width: 900px) {
    order: 2;
    text-align: center;
    align-items: center;
  }
`;

const Eyebrow = styled.span`
  font-size: 0.85rem;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 2px;
  color: var(--color-primary);
  margin-bottom: 1rem;
  display: inline-block;
  background: rgba(0, 200, 81, 0.1);
  padding: 0.4rem 1rem;
  border-radius: 50px;
`;

const HeroHeading = styled.h1`
  font-size: 3.5rem;
  font-weight: 800;
  color: var(--color-text);
  margin: 0 0 1rem 0;
  line-height: 1.15;

  @media (max-width: 1024px) {
    font-size: 3rem;
  }

  @media (max-width: 768px) {
    font-size: 2.25rem;
  }
`;

const HeroSubheading = styled.h3`
  font-size: 1.2rem;
  font-weight: 600;
  color: var(--color-text-secondary);
  line-height: 1.5;
  margin: 0 0 1.5rem 0;

  @media (max-width: 768px) {
    font-size: 1.1rem;
  }
`;

const HeroDescription = styled.p`
  font-size: 1.05rem;
  color: var(--color-text-muted);
  line-height: 1.6;
  margin: 0 0 2.5rem 0;
  max-width: 90%;

  @media (max-width: 900px) {
    max-width: 100%;
  }
`;

const CTAButton = styled.a`
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.75rem;
  background: var(--color-primary);
  color: #000;
  padding: 1.1rem 2.5rem;
  border-radius: 50px;
  font-size: 1.05rem;
  font-weight: 800;
  text-decoration: none;
  transition: all 0.3s ease;
  box-shadow: 0 4px 15px rgba(0, 200, 81, 0.2);
  align-self: flex-start;

  &.center {
    align-self: center;
  }

  &:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 25px rgba(0, 200, 81, 0.35);
    background: var(--color-primary-dark);
  }

  @media (max-width: 900px) {
    width: 100%;
    align-self: center;
  }
`;

const HeroImageArea = styled.div`
  width: 100%;

  @media (max-width: 900px) {
    order: 1;
  }
`;

const ImageWrapper = styled.div`
  width: 100%;
  border-radius: 20px;
  overflow: hidden;
  box-shadow: 0 15px 40px rgba(0, 0, 0, 0.08);

  img {
    width: 100%;
    height: auto;
    object-fit: cover;
    display: block;
  }

  &.tall {
    height: 500px;
    img {
      height: 100%;
    }
  }

  @media (max-width: 768px) {
    border-radius: 16px;
    &.tall {
      height: 350px;
    }
  }
`;

// --- 2️⃣ SMART ENERGY HUB CONCEPT ---
const HubSection = styled.section`
  padding: 100px 0;
  background-color: var(--color-bg);
`;

const FlowDiagram = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  max-width: 1000px;
  margin: 40px auto 0;
  padding: 2rem;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: 24px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.03);

  @media (max-width: 768px) {
    flex-direction: column;
    padding: 2rem 1.5rem;
    gap: 1rem;
  }
`;

const FlowNode = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: 1rem;
  flex: 1;

  .icon-circle {
    width: 70px;
    height: 70px;
    background: var(--color-surface-secondary);
    border: 1px solid var(--color-border-light);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--color-text-muted);
    transition: all 0.3s ease;
  }

  span {
    font-size: 1rem;
    font-weight: 700;
    color: var(--color-text);
  }

  &.highlight {
    .icon-circle {
      width: 90px;
      height: 90px;
      background: var(--color-primary);
      color: #000;
      border-color: var(--color-primary-dark);
      box-shadow: 0 8px 25px rgba(0, 200, 81, 0.3);
    }
    span {
      color: var(--color-primary-dark);
      font-size: 1.1rem;
    }
  }

  @media (max-width: 768px) {
    flex-direction: row;
    width: 100%;
    justify-content: flex-start;
    padding-left: 10%;

    &.highlight .icon-circle {
      width: 70px;
      height: 70px;
    }
  }
`;

const FlowArrow = styled.div`
  color: var(--color-border);
  padding: 0 1rem;

  @media (max-width: 768px) {
    transform: rotate(90deg);
    padding: 0.5rem 0;
  }
`;

// --- 3️⃣ RAPID MPPT TECHNOLOGY ---
const MpptSection = styled.section`
  padding: 100px 0;
  background-color: var(--color-surface-secondary);
  border-top: 1px solid var(--color-border-light);
  border-bottom: 1px solid var(--color-border-light);
`;

const SplitLayout = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 60px;
  align-items: center;

  @media (max-width: 900px) {
    grid-template-columns: 1fr;
    gap: 40px;

    &.reverse-mobile {
      display: flex;
      flex-direction: column-reverse;
    }
  }
`;

const MpptImageArea = styled.div`
  width: 100%;
`;

const MpptContent = styled.div`
  display: flex;
  flex-direction: column;
`;

const FeatureCardsWrapper = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
`;

const MpptFeatureCard = styled.div`
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: 16px;
  padding: 1.5rem;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.02);

  p {
    font-size: 0.95rem;
    color: var(--color-text-secondary);
    line-height: 1.5;
    margin: 0;
  }
`;

const FeatureHeader = styled.div`
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-bottom: 0.75rem;

  .feature-icon {
    color: var(--color-primary);
  }

  h4 {
    font-size: 1.15rem;
    font-weight: 700;
    color: var(--color-text);
    margin: 0;
  }
`;

// --- 4️⃣ SAFETY & COMPLIANCE SYSTEMS ---
const SafetySection = styled.section`
  padding: 120px 0;
  background-color: var(--color-bg);
`;

const Grid3Col = styled.div`
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 32px;

  @media (max-width: 1024px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
    gap: 24px;
  }
`;

const SafetyCard = styled.div`
  background: var(--color-surface);
  border: 1px solid var(--color-border-light);
  border-radius: 16px;
  padding: 2.5rem 2rem;
  display: flex;
  flex-direction: column;
  transition:
    transform 0.3s ease,
    box-shadow 0.3s ease;
  height: 100%;

  &:hover {
    transform: translateY(-4px);
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.05);
    border-color: var(--color-border);
  }
`;

const IconBox = styled.div`
  width: 56px;
  height: 56px;
  background: rgba(0, 200, 81, 0.08);
  color: var(--color-primary);
  border-radius: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 1.5rem;

  &.light {
    background: var(--color-surface-secondary);
    border: 1px solid var(--color-border);
  }
`;

const CardTitle = styled.h3`
  font-size: 1.25rem;
  font-weight: 800;
  color: var(--color-text);
  margin: 0 0 1rem 0;
`;

const CardDesc = styled.p`
  font-size: 0.95rem;
  color: var(--color-text-secondary);
  line-height: 1.6;
  margin: 0;
`;

// --- 5️⃣ PROFESSIONAL INVERTER ENGINEERING ---
const EngineeringSection = styled.section`
  padding: 100px 0;
  background-color: var(--color-surface-secondary);
  border-top: 1px solid var(--color-border-light);
`;

const EngineeringContent = styled.div`
  display: flex;
  flex-direction: column;
`;

const EngineeringImageArea = styled.div`
  width: 100%;
`;

const EngineeringList = styled.div`
  display: flex;
  flex-direction: column;
  gap: 2rem;
`;

const EngineeringItem = styled.div`
  display: flex;
  align-items: flex-start;
  gap: 1.25rem;

  h4 {
    font-size: 1.15rem;
    font-weight: 700;
    color: var(--color-text);
    margin: 0 0 0.5rem 0;
  }

  p {
    font-size: 0.95rem;
    color: var(--color-text-secondary);
    line-height: 1.5;
    margin: 0;
  }
`;

const EngineeringIcon = styled.div`
  background: var(--color-surface);
  color: var(--color-primary);
  padding: 0.75rem;
  border-radius: 12px;
  border: 1px solid var(--color-border-light);
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
`;

// --- 6️⃣ GRID INTERACTION & ENERGY AUTONOMY ---
const GridInteractionSection = styled.section`
  padding: 120px 0;
  background-color: var(--color-bg);
  border-top: 1px solid var(--color-border-light);
`;

const InteractionCard = styled.div`
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: 16px;
  padding: 2rem;
  display: flex;
  flex-direction: column;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.02);
`;

const InteractionHeader = styled.div`
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 1.25rem;

  h3 {
    margin: 0;
    font-size: 1.15rem;
  }

  .icon-box {
    margin-bottom: 0;
  }
`;

// --- FINAL CTA SECTION ---
const CtaSection = styled.section`
  padding: 100px 0;
  background: linear-gradient(
    135deg,
    var(--color-surface-secondary) 0%,
    var(--color-bg) 100%
  );
  border-top: 1px solid var(--color-border-light);
  text-align: center;
`;

const CtaWrapper = styled.div`
  max-width: 700px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const CtaHeading = styled.h3`
  font-size: 2.25rem;
  font-weight: 800;
  color: var(--color-text);
  margin-bottom: 1rem;

  @media (max-width: 768px) {
    font-size: 1.75rem;
  }
`;

const CtaSubtext = styled.p`
  font-size: 1.1rem;
  color: var(--color-text-secondary);
  line-height: 1.6;
  margin: 0 0 2.5rem 0;

  @media (max-width: 768px) {
    font-size: 1rem;
  }
`;
